### ISSUE TITLE
Issue (Questions?) Akira Takeuchi

### ISSUE THREAD

**Issue by 50516021** [Rainekie/Web-based-Technical-Ear-Training#1]
Chrome on Macbook pro
#'three modulation conditions' = stimuli ? (tehre are only 2 of them)
#There is a gap about 2 sec after pressing 'Start' to the sound begin
#Is it ok that I can change 'condition' or 'stimuli' during the sound is playing

**Comment by Rainekie** [comment]
Thanks!

`#'three modulation conditions' = stimuli ? (tehre are only 2 of them)`
-> That is a previous implementation's text. I will change it.

`#There is a gap about 2 sec after pressing 'Start' to the sound begin`
-> I have noticed that some low-speed network situations take a buffering process longer than expected so I put the 2-sec delay intentionally to ensure the process is completed.

`#Is it ok that I can change 'condition' or 'stimuli' during the sound is playing`
-> I don't think that is a common situation but I will add a function to disable the radio buttons to choose the options when a user pressed the "Start" button.
